name: oop-web build
on:
  push:
    paths:
      - "oop/src/**/*.html"
      - "oop/src/**/*.ts"
      - "oop/src/**/*.js"
      - "oop/src/**/*.scss"
      - "oop/package*.json"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./oop
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test
      # - name: LINTing
      #   run: npm run test:lint
      # - name: OpenAPI Schema
      #   run: npm run test:schema
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./oop
    needs: [test]
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Check directory
        run: | 
          pwd
          ls
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: "true"
  image-build:
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     shell: bash
    #     working-directory: ../../../
    #     working-directory: ./oop
    needs: [test, build]
    steps:
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          oc: "latest"
      - name: Check that tools-installer works (3)
        run: oc version
      - name: Artifact Build
        env:
          NAMESPACE: a3c641-tools
          BUILD_NAME: oop-web-artifact-build
          IMAGE_NAME: oop-web-artifacts
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
      - name: Generate/Tag Artifact Build
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          oc: "latest"
      - run: |
          oc version
          oc start-build oop-web-artifact-build -n a3c641-tools --follow
          oc tag -n a3c641-tools a3c641-tools/oop-web-artifacts:latest a3c641-tools/oop-web-artifacts:dev
      # - name: Image Build
      #   env:
      #     NAMESPACE: a3c641-tools
      #     BUILD_NAME: oop-web-image-build
      #     IMAGE_NAME: oop-web
      #   uses: redhat-developer/openshift-actions@v1.1
      #   with:
      #     version: "latest"
      #     openshift_server_url: ${{ secrets.OpenShiftServerURL}}
      #     parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
      # - name: Generate/Tag Image Build
      #   uses: redhat-actions/openshift-tools-installer@v1
      #   with:
      #     source: "mirror"
      #     oc: "latest"
      - run: |
          pwd
          ls
          oc version
        # 'oc start-build ${BUILD_NAME} -n ${NAMESPACE} --follow'
        # 'oc tag -n ${NAMESPACE} ${NAMESPACE}/${IMAGE_NAME}:latest ${NAMESPACE}/${IMAGE_NAME}:dev'
