name: test aop-web tag
on:
  push:
    paths:
      - "aop/src/**/*.html"
      - "aop/src/**/*.ts"
      - "aop/src/**/*.js"
      - "aop/src/**/*.scss"
      - "aop/package*.json"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./aop
jobs:
  image-tag:
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Artifact tag
        env:
          NAMESPACE: a3c641-tools
          BUILD_NAME: aop-web-artifact-build
          IMAGE_NAME: aop-web-artifacts
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'tag -n ${NAMESPACE} ${NAMESPACE}/${IMAGE_NAME}:latest ${NAMESPACE}/${IMAGE_NAME}:dev'
      - name: Image tag
        env:
          NAMESPACE: a3c641-tools
          BUILD_NAME: aop-web-image-build
          IMAGE_NAME: aop-web
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'tag -n ${NAMESPACE} ${NAMESPACE}/${IMAGE_NAME}:latest ${NAMESPACE}/${IMAGE_NAME}:dev'
